#!/bin/bash

IMAGE_NAME=digitelts/alastria-node-t:latest

DIRECTORY="./config"

NODE_NAME=$(< $DIRECTORY/NODE_NAME)
NODE_TYPE=$(< $DIRECTORY/NODE_TYPE)
MONITOR_ENABLED=$(< $DIRECTORY/MONITOR_ENABLED)
ENABLE_CONSTELLATION=$(< $DIRECTORY/ENABLE_CONSTELLATION)
DATA_DIR=$( <$DIRECTORY/DATA_DIR)
ACCESS_POINT_DIR=$( <$DIRECTORY/ACCESS_POINT_DIR)
EXTRA_DOCKER_ARGUMENTS=${EXTRA_DOCKER_ARGUMENTS:-}

# docker rm $NODE_NAME

docker create --name $NODE_NAME \
      -v $DATA_DIR:/root/alastria \
      -p 21000:21000 -p 21000:21000/udp -p 22000:22000 -p 9000:9000 -p 8443:8443 \
      -e NODE_NAME=$NODE_NAME \
      -e NODE_TYPE=$NODE_TYPE \
      -e MONITOR_ENABLED=$MONITOR_ENABLED \
      -e ENABLE_CONSTELLATION=$ENABLE_CONSTELLATION \
      ${IMAGE_NAME}
